### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by obrsk** [reqweb/CBRcurrency#1]
Подскажи пожалуйста, кэширует twig  данные из xml или каждый раз обрабатывает их заново? На основе твоего плагина сделал вставку данных (из xml, который размещен в user) на разные страницы и вопрос поэтому интересен. Спасибо.

**Comment by reqweb** [comment]
Я не писал ничего для кэширования, потому что курсы валют обновляются, и кэш может показать несколько устаревшее значение, что будет не очень правильно. Если вам для вашего случая нужен кэш, здесь описано как это сделать - [Using Cache in your own plugins](https://learn.getgrav.org/16/cookbook/plugin-recipes#using-cache-in-your-own-plugins)
